/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Phoenix(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/phoenix_bird.glb");
  const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
    
    // Make materials brighter and more emissive
    if (materials.MatI_Ride_FengHuang_01a) {
      materials.MatI_Ride_FengHuang_01a.emissive = { r: 0.2, g: 0.1, b: 0.05 };
      materials.MatI_Ride_FengHuang_01a.emissiveIntensity = 0.3;
    }
    if (materials.MatI_Ride_FengHuang_01b) {
      materials.MatI_Ride_FengHuang_01b.emissive = { r: 0.2, g: 0.1, b: 0.05 };
      materials.MatI_Ride_FengHuang_01b.emissiveIntensity = 0.3;
    }
  }, [actions, animations, materials]);

  useFrame((state) => {
    if (group.current) {
      // Rotate on all axes like Earth
      group.current.rotation.x = Math.sin(state.clock.elapsedTime * 0.1) * 0.1;
      group.current.rotation.y += 0.005; // Continuous Y rotation
      group.current.rotation.z = Math.cos(state.clock.elapsedTime * 0.1) * 0.05;
    }
  });
  
  return (
    <>
      {/* Add lighting to illuminate the phoenix */}
      <pointLight position={[0, 0, 0]} intensity={2} color="#ffffff" />
      <ambientLight intensity={0.8} />
      <directionalLight position={[5, 5, 5]} intensity={1} />
      
      <group
        ref={group}
        {...props}
        dispose={null}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={props.scale || 0.002}
        position={props.position || [0, -0.5, 0]}
      >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[-0.625, 0, -17.137]}
          rotation={[-Math.PI / 2, 0, 0.053]}>
          <group name="5f59736c86d4457fa045aec4aea6b7e0fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.MatI_Ride_FengHuang_01a}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.MatI_Ride_FengHuang_01b}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="AMesh_Ride_FengHuang_01" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      </group>
    </>
  );
}

useGLTF.preload("/models/phoenix_bird.glb");
